MVCLogin/Models/course.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class course
    {
        public int id { get; set; }
        [DisplayName("Course Code")]
        public string course_id { get; set; }
        [DisplayName("Teacher ID")]
        public string teacher_id { get; set; }
        [DisplayName("Student Number")]
        public string student_d { get; set; }
        public string CheckDetailsMessage { get; set; }
    }
}

MVCLogin/Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLogin.Controllers
{
    public class AttendanceController : Controller
    {
        //
        // GET: /Attendance/
        public ActionResult Index()
        {
            return View();
        }
	}
}

MVCLogin/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLogin.Controllers
{
    public class CourseController : Controller
    {
        //
        // GET: /Course/
        public ActionResult Index()
        {
            return View();
        }
	}
}

MVCLogin/Views/Course/Index.cshtml
@model MVCLogin.Models.course
@{
    Layout = null;

    }
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div id="Login-div">
        @using (Html.BeginForm("Index", "Attendance", FormMethod.Post))
        {


            <table>
                <tr>
                    <td></td>
                    <td style="text-decoration-line:underline">Login pge</td>

                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.student_d)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.student_d)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.student_d)</td>
                </tr>


                <tr>
                    <td>
                        @Html.LabelFor(model => model.course_id)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.course_id)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.course_id)</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.teacher_id)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.teacher_id)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.teacher_id)</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <label class="field-validation-error">@Html.DisplayFor(model => model.CheckDetailsMessage)</label>
                    </td>
                </tr>

                <tr>
                    <td>
                        <input type="submit" name="name" value="Submit" />
                        @*<input type="Reset" name="name" value="Clear" />*@
                    </td>
                </tr>

            </table>
        }


    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <div>
    </div>
</body>
</html>